### ISSUE TITLE
New feature: property moonPhase

### ISSUE THREAD

**Issue by marcosatanaka** [dvdme/forecastio-lib-java#15]
The property **moonPhase** it's not available in `FIODataPoint`. I implemented and tested the new feature locally on my computer. May I fork the project and perform a pull request to yours?

**Comment by dvdme** [comment]
This is odd, I probably forgot it because I made updates after the moonPhase property was available. And I remeber this property.
Anyway, sure you can make a pull request. 
Just follow the same pattern, as it returns a double between 0 and 1 it should work with something like

```java
public Double moonPhase(){
		if(this.datapoint.containsKey("moonPhase"))
			return asDouble(this.datapoint.get("moonPhase"));
		else
			return null;
	}
``` 

I have another small update I want to make and I have to update in maven in the near future.

**Comment by dvdme** [comment]
Closing this because I just merged your pull request.
